In [1]:
# simRemoteApi.start(19999)
try:
    import sim
except:
    print ('--------------------------------------------------------------')
    print ('"sim.py" could not be imported. This means very probably that')
    print ('either "sim.py" or the remoteApi library could not be found.')
    print ('Make sure both are in the same folder as this file,')
    print ('or appropriately adjust the file "sim.py"')
    print ('--------------------------------------------------------------')
    print ('')

import time
import random

In [7]:
startClientID = sim.simxStart('127.0.0.1', 19997, True, False, 5000, 5)
res = sim.simxStartSimulation(startClientID, sim.simx_opmode_blocking)
if res == sim.simx_return_ok:
    print('Simulation started successfully')

Simulation started successfully


In [4]:
res = sim.simxStopSimulation(startClientID, sim.simx_opmode_blocking)
if res == sim.simx_return_ok:
    print('Stop signal sent')
sim.simxFinish(startClientID)

In [5]:
sim.simxFinish(-1)
print ('Program started')
sim.simxFinish(-1) # just in case, close all opened connections
clientID=sim.simxStart('127.0.0.1',19999,True,True,5000,5) # Connect to CoppeliaSim
if clientID!=-1:
    print ('Connected to remote API server')

Program started


In [8]:
res = sim.simxStartSimulation(clientID, sim.simx_opmode_oneshot)
print(res)

1


In [11]:
robotname = 'Doggy'
robotErro, robot = sim.simxGetObjectHandle(clientID, robotname, sim.simx_opmode_oneshot_wait)
targetErro, target = sim.simxGetObjectHandle(clientID, "Target", sim.simx_opmode_oneshot_wait)
print(f"Robot: {robotErro}\n Target:{targetErro}")

Robot: 64
 Target:64


In [12]:
[erro, robot_RR_upper_motor] = sim.simxGetObjectHandle(clientID, "RR_upper_leg_joint",sim.simx_opmode_oneshot_wait)
[erro, robot_RR_lower_motor] = sim.simxGetObjectHandle(clientID, "RR_lower_leg_joint", sim.simx_opmode_oneshot_wait)
    
[erro, robot_RL_upper_motor] = sim.simxGetObjectHandle(clientID, "RL_upper_leg_joint",sim.simx_opmode_oneshot_wait)
[erro, robot_RL_lower_motor] = sim.simxGetObjectHandle(clientID, "RL_lower_leg_joint", sim.simx_opmode_oneshot_wait)

[erro, robot_FR_upper_motor] = sim.simxGetObjectHandle(clientID, "FR_upper_leg_joint",sim.simx_opmode_oneshot_wait)
[erro, robot_FR_lower_motor] = sim.simxGetObjectHandle(clientID, "FR_lower_leg_joint", sim.simx_opmode_oneshot_wait)

[erro, robot_FL_upper_motor] = sim.simxGetObjectHandle(clientID, "FL_upper_leg_joint",sim.simx_opmode_oneshot_wait)
[erro, robot_FL_lower_motor] = sim.simxGetObjectHandle(clientID, "FL_lower_leg_joint", sim.simx_opmode_oneshot_wait)

sim.simxSetJointTargetVelocity(clientID, robot_RR_upper_motor, random.random()-0.5, sim.simx_opmode_oneshot)
sim.simxSetJointTargetVelocity(clientID, robot_RR_lower_motor, random.random()-0.5, sim.simx_opmode_oneshot)

sim.simxSetJointTargetVelocity(clientID, robot_RL_upper_motor, random.random()-0.5, sim.simx_opmode_oneshot)
sim.simxSetJointTargetVelocity(clientID, robot_RL_lower_motor, random.random()-0.5, sim.simx_opmode_oneshot)

sim.simxSetJointTargetVelocity(clientID, robot_FR_upper_motor, random.random()-0.5, sim.simx_opmode_oneshot)
sim.simxSetJointTargetVelocity(clientID, robot_FR_lower_motor, random.random()-0.5, sim.simx_opmode_oneshot)

sim.simxSetJointTargetVelocity(clientID, robot_FL_upper_motor, random.random()-0.5, sim.simx_opmode_oneshot)
sim.simxSetJointTargetVelocity(clientID, robot_FL_lower_motor, random.random()-0.5, sim.simx_opmode_oneshot)


64

In [10]:
erro, distance_vector = sim.simxGetObjectPosition(clientID,robot,target,sim.simx_opmode_oneshot_wait)
print(distance_vector)

[0.0, 0.0, 0.0]


# Neural network

### Inputs: 
Velocidades e posições das 8 juntas - 16 inputs

## Outputs:
Novas velocidades para cada uma das 8 juntas - 8 outputs

for epoch in range epochs:

    model.train()
    y_pred = model(x_train)
    loss = loss_fn(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    model.eval()


In [5]:
from pathlib import Path

MODEL_PATH = Path("models")
MODEL_PATH.mkdir(parents=True,exist_ok=True)

MODEL_NAME = "nome_do_modelo.pth"
MODEL_SAVE_PATH = MODEL_PATH/MODEL_NAME

print(f"Saving model to: {MODEL_SAVE_PATH}")
torch.save(obj=model.state_dict(),f=MODEL_SAVE_PATH)

PosixPath('models/nome_do_modelo.pth')

In [8]:
import torch
from torch import nn
import matplotlib.pyplot as plt


In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [19]:
weight = 0.7
bias = 0.3

start = 0
end = 1
step = 0.02

x = torch.arange(start,end,step).unsqueeze(dim=1)
y = weight*x+bias

x[:10],y[:10]


(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [20]:
#Split data
train_split = int(0.8*len(x))
x_train,y_train = x[:train_split],y[:train_split]
x_test,y_test = x[train_split:],y[train_split:]

40

In [21]:
def plot_predicitions(train_data = x_train,
                      train_labels=y_train,
                      test_data = x_test,
                      test_labels = y_test,
                      predictions = None):
    plt.figure(figsize=(10,7))

    plt.scatter(train_data,train_labels,c="b",s=4,label="Training data")
    plt.scatter(test_data,test_labels,c="g",s=4,label="Testing data")

    if predictions is not None:
        plt.scatter(test_data,predictions,c="r",s=4,label="Predictions")
    plt.legend(prop={"size":14})

In [25]:
class LinearRegressionModelV0(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer = nn.Linear(in_features=1,
                                      out_features=1)
    def forward(self,x:torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

In [26]:
torch.manual_seed(42)
model_1 = LinearRegressionModelV0()
model_1,model_1.state_dict()

(LinearRegressionModelV0(
   (linear_layer): Linear(in_features=1, out_features=1, bias=True)
 ),
 OrderedDict([('linear_layer.weight', tensor([[0.7645]])),
              ('linear_layer.bias', tensor([0.8300]))]))

In [1]:
import numpy as np
np.arange(0,0+3)

array([0, 1, 2])

In [2]:
np.random.choice(100, 10, replace=False)

array([58, 99, 35, 55, 61, 29,  2, 10,  4, 16])

In [5]:
import numpy as np
import torch

# Criando tensores de exemplo
torch.manual_seed(42)
tensor_100x24 = np.random.rand(100, 24)  # Exemplo com valores aleatórios
tensor_100x1 = np.random.choice([False, True], size=(100, 1))  # Valores aleatórios True/False

# Criando a linha de zeros
linha_zeros = np.zeros((1, 24))

# Modificando as linhas onde tensor_100x1 é True
tensor_100x24[tensor_100x1.flatten()] = linha_zeros

# Exibir resultados
print("Tensor modificado:\n", tensor_100x24)

Tensor modificado:
 [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.07348694 0.270696   0.58042041 ... 0.04785368 0.14602785 0.0344438 ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.58109919 0.77072447 0.69082275 ... 0.958781   0.97614551 0.50475656]
 [0.54673482 0.95409053 0.12827211 ... 0.53003334 0.27557144 0.34095304]
 [0.09063041 0.07766533 0.38603696 ... 0.78753368 0.94578352 0.4199863 ]]


In [27]:
import torch

# Definição das variáveis
action_batch = torch.tensor([[1, 2, 4], [0, 2, 5]])
reward_batch = torch.tensor([[20], [10]])
gamma = 0.9
        
q_eval = torch.tensor([[1, 2, 3, 4, 5, 6], [0, 1, 2, 3, 4, 5]],dtype=torch.float32)

q_real = torch.clone(q_eval)

q_next = torch.tensor([[2, 4, 6, 8, 10, 12], [0, 2, 4, 6, 8, 10]])
terminal_batch = torch.tensor([True, False])

# Corrigindo a substituição de valores em q_next
linha_zeros = torch.zeros((1, 6),dtype=torch.long)  # Mudando para tensor PyTorch
q_next[terminal_batch.flatten()] = linha_zeros

q_next_actions = torch.tensor([[0, 2, 5], [1, 3, 5]])

q_next = q_next.float()  # Converte para float
q_next_mean_reward = torch.mean(torch.gather(q_next, 1, q_next_actions), dim=1)


# Calculando o alvo de Q
q_target = reward_batch + gamma * q_next_mean_reward.unsqueeze(1)  # Garantindo a forma correta

# Corrigindo indexação
rows = torch.arange(2).unsqueeze(1)  # Agora é um tensor PyTorch
print(f"Q real antes mudança: {q_real}")
q_real[rows, action_batch] = q_target
print(f"Q real pós mudança: {q_real}")


print(f"Action batch: {action_batch}")
print(f"Reward batch: {reward_batch}")
print(f"Q eval: {q_eval}")
print(f"Q real: {q_real}")
print(f"Terminal batch: {terminal_batch}")
print(f"Q next: {q_next}")
print(f"Q next actions: {q_next_actions}")
print(f"Q next mean reward: {q_next_mean_reward}")
print(f"q target: {q_target}")





print("q_real atualizado:\n", q_real)


Q real antes mudança: tensor([[1., 2., 3., 4., 5., 6.],
        [0., 1., 2., 3., 4., 5.]])
Q real pós mudança: tensor([[ 1.0000, 20.0000, 20.0000,  4.0000, 20.0000,  6.0000],
        [15.4000,  1.0000, 15.4000,  3.0000,  4.0000, 15.4000]])
Action batch: tensor([[1, 2, 4],
        [0, 2, 5]])
Reward batch: tensor([[20],
        [10]])
Q eval: tensor([[1., 2., 3., 4., 5., 6.],
        [0., 1., 2., 3., 4., 5.]])
Q real: tensor([[ 1.0000, 20.0000, 20.0000,  4.0000, 20.0000,  6.0000],
        [15.4000,  1.0000, 15.4000,  3.0000,  4.0000, 15.4000]])
Terminal batch: tensor([ True, False])
Q next: tensor([[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  4.,  6.,  8., 10.]])
Q next actions: tensor([[0, 2, 5],
        [1, 3, 5]])
Q next mean reward: tensor([0., 6.])
q target: tensor([[20.0000],
        [15.4000]])
q_real atualizado:
 tensor([[ 1.0000, 20.0000, 20.0000,  4.0000, 20.0000,  6.0000],
        [15.4000,  1.0000, 15.4000,  3.0000,  4.0000, 15.4000]])


In [36]:
import torch

tensor = torch.tensor([1, 2, 3, 2, 3, 4, 1, 5, 2])
index = torch.argmax(tensor).item()
print(index)


7


In [38]:
import torch

jointHandler = {"j1": 1,
                 "j2": 2,
                 "j3": 3,
                 "j4": 4,
                 "j5": 5,
                 "j6": 6,
                 "j7": 7,
                 "j8": 8,}
t = torch.tensor([ 2,  3,  7, 10, 12, 15, 19, 21])
for joint_index, joint in enumerate(jointHandler.values()):
        print(f"Numero passado: {t[joint_index]-3*joint_index}")





Numero passado: 2
Numero passado: 0
Numero passado: 1
Numero passado: 1
Numero passado: 0
Numero passado: 0
Numero passado: 1
Numero passado: 0


In [2]:
import torch

test = torch.tensor([ 2.5200e+01, -6.5493e-01,  2.5751e-01, -1.4703e+00, -1.6603e+00,
         6.7469e-01,  3.1171e+00,  5.3616e-01,  2.9093e-04,  5.9609e-01,
        -1.4699e-03,  1.7188e+00, -6.5884e-01, -2.3517e+00, -2.2441e-01,
         1.4108e+00, -2.3054e+00, -2.6023e-01,  2.8685e+00,  7.8008e-01,
         9.7075e-01])

group = test[18:21+3]

print(group)

tensor([2.8685, 0.7801, 0.9707])


In [1]:
[0]*24

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [4]:
import torch
tensor = torch.rand(24)  # Números aleatórios entre 0 e 1
print(tensor)
# Reformulando o tensor para ter forma (8,3), ou seja, 8 grupos de 3 elementos


tensor_reshaped = tensor.view(-1, 3)
print(tensor_reshaped[1])
# Pegando o índice do maior valor dentro de cada grupo
max_indices = torch.argmax(tensor_reshaped, dim=1)
print(max_indices)

tensor([0.2253, 0.5000, 0.6381, 0.8461, 0.5591, 0.3515, 0.6236, 0.2154, 0.0032,
        0.2356, 0.3536, 0.1499, 0.7128, 0.7189, 0.4946, 0.5133, 0.3406, 0.4193,
        0.9746, 0.1047, 0.9454, 0.9802, 0.4151, 0.7260])
tensor([0.8461, 0.5591, 0.3515])
tensor([2, 0, 0, 1, 1, 0, 0, 0])


In [2]:
t = 16*3.6
o = 18*3.6
d = 400
temp = t/d
temp2 = o/d

print(temp)
print(temp2)

0.14400000000000002
0.162


In [2]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
from SimulationControl import createSimulation
sim = createSimulation("cpu")
sim.reset()

array([-25.        ,   0.        ,   0.398     ,   0.        ,
         0.        ,   0.        ,   0.78539816,   0.        ,
         0.78539816,   0.        ,   0.78539816,   0.        ,
         0.78539816,   0.        ,  -1.57079633,   0.        ,
        -1.57079633,   0.        ,  -1.57079633,   0.        ,
        -1.57079633,   0.        ,   1.        ])

In [18]:
while True:
    sim.step([2,0,0,0,0,0,0,0])

ZMQError: Operation cannot be accomplished in current state

In [1]:
from coppeliasim_zmqremoteapi_client import *
import math

client = RemoteAPIClient()
sim = client.require('sim')
robot = sim.getObject('/Doggy/')
target = sim.getObject('/Target')
sim.startSimulation()

In [2]:
pitch_angle =sim.getObjectOrientation(robot, -1)[1]
roll_angle = sim.getObjectOrientation(robot, -1)[0]
yaw_angle = sim.getObjectOrientation(robot, -1)[2] #para frente é 3.14
max_angle = math.pi/3
stable = abs(yaw_angle) < max_angle and abs(pitch_angle) < max_angle and abs(roll_angle) < max_angle
print(yaw_angle)
print(pitch_angle)
print(roll_angle)
print(stable)

-0.0
1.241673430740775e-12
-0.0
True


In [64]:
jointList = ["RR_upper_leg_joint",
        "RL_upper_leg_joint",
        "FR_upper_leg_joint",
        "FL_upper_leg_joint",
        "RR_lower_leg_joint",
        "RL_lower_leg_joint",
        "FR_lower_leg_joint",
        "FL_lower_leg_joint"]

handleDict: dict[str,int] = {}
for name in jointList:
    path = f"/Doggy/{name}"
    handleDict[name] = sim.getObject(path)

def translateAction(sim, action:int,joint):
    match action:
        case 0:
            sim.setJointTargetVelocity(joint, -math.pi/3)
        case 1:
            sim.setJointTargetVelocity(joint, 0)
        case 2:
            sim.setJointTargetVelocity(joint, math.pi/3)
        case _:
            raise ValueError(f"Numero passado {action} para translate action não corresponde as ações")
def step(actions):
    for joint_index, jointName in enumerate(jointList):
            joint = handleDict[jointName]
            translateAction(sim,action = actions[joint_index], joint = joint)


In [3]:
sim.getSimulationTime()

21.050000000000164

In [69]:
sim.getJointPosition(handleDict[jointList[0]])

0.7853981633975

In [4]:
sim.getObjectPosition(robot, target)

[-24.99999999999983, 0.0, 0.39800000000497326]

In [9]:

[roll,pitch,yaw] = sim.getObjectOrientation(robot, -1)

sum([abs(roll),abs(pitch),abs(yaw)])



1.570796326794

In [82]:
while True:
    [vx, vy, vz], [wx, wy, wz] = sim.getObjectVelocity(robot)
    print(vx)

0.7884897585732884

In [108]:
error, joint_speed = sim.getObjectFloatParameter(91, sim.jointfloatparam_velocity)
print(error)
print(joint_speed)

1
0.004062689210741297


In [113]:
disc = 0.99
steps = 50
r = 0.3

curr_disc = 1
final_value = 0
for step in range(steps):
    new_r = r * curr_disc  # Aplica o desconto à recompensa fixa
    final_value += new_r
    curr_disc *= disc  # Atualiza o fator de desconto

print(final_value)


11.849817985873894


In [115]:
import numpy as np

valores = [-1.0148, -1.0797, -0.8059, -1.0090, -1.1926, -0.7421, -1.0160, -1.0877]
resultado = np.exp(valores)

print(resultado)


[0.36247492 0.33969742 0.44668573 0.36458338 0.30343132 0.47611303
 0.36204021 0.33699068]


In [117]:
import numpy as np

a = np.array([0.9603, 0.9438, 1.0798, 0.9606, 0.9409])
b = np.array([2.9900, 2.4874, -2.0748, 2.5695, 2.6272])

result = a * b
print(result)

c = [ 2.8712,  2.3477, -2.2404,  2.4682,  2.4719]


[ 2.871297    2.34760812 -2.24036904  2.4682617   2.47193248]


In [3]:
import numpy as np

np.array([0.9885, 1.0781, 1.0939, 0.9132, 1.0079, 0.9547, 1.1323, 1.0077])* 1.3229

array([1.30768665, 1.42621849, 1.44712031, 1.20807228, 1.33335091,
       1.26297263, 1.49791967, 1.33308633])

In [11]:
_,teste = _,0

In [4]:
from coppeliasim_zmqremoteapi_client import *
import math

client = RemoteAPIClient()
sim = client.require('sim')
robot = sim.getObject('/Doggy/')
target = sim.getObject('/Target')

In [3]:
sim.getObjectOrientation(robot, -1)

[0.04742715805889403, 0.39419731601833674, 1.4367003303574286]

In [6]:
dx, dy, dz = sim.getObjectPosition(sim.getObject('/Doggy/'),sim.getObject('/Target/'))
print(dx,dy,dz)

-24.65565164800541 0.06173674134885998 0.26485028103466834


In [19]:
dx, dy, dz = sim.getObjectPosition(sim.getObject('/Doggy/RR_lower_leg_joint'),sim.getObject('/Doggy/RR_upper_leg_joint'))
print(dx,dy,dz)


0.0 0.25 4.440892098500626e-16


In [20]:
dx, dy, dz = sim.getObjectPosition(sim.getObject('/Doggy/RR_foot_joint'),sim.getObject('/Doggy/RR_lower_leg_joint'))
print(dx,dy,dz)


0.0 0.2500000000000018 0.0


In [28]:
deg= sim.getJointPosition(sim.getObject('/Doggy/RR_upper_leg_joint'))
print(deg)


0.7853981633975


In [29]:
deg= sim.getJointPosition(sim.getObject('/Doggy/RR_lower_leg_joint'))
print(deg)

-1.570796326795


In [2]:
import numpy as np
from coppeliasim_zmqremoteapi_client import *
import math

client = RemoteAPIClient()
sim = client.require('sim')
robot = sim.getObject('/Doggy/')
target = sim.getObject('/Target')

vertex_2_center = {}
for vertex in ["RL","RR","FL","FR"]:
    vertex_2_center_temp = sim.getObjectPosition(sim.getObject(f'/Doggy/{vertex}_upper_leg_joint'),sim.getObject('/Doggy/base_link_visual'))
    vertex_2_center[vertex] = {}
    vertex_2_center[vertex]["x"] = vertex_2_center_temp[0]
    vertex_2_center[vertex]["y"] = vertex_2_center_temp[1]
    vertex_2_center[vertex]["z"] = vertex_2_center_temp[2]
_,upper_leg_lenght, _ = sim.getObjectPosition(sim.getObject('/Doggy/RR_lower_leg_joint'),sim.getObject('/Doggy/RR_upper_leg_joint'))
_,lower_leg_lenght, _ = sim.getObjectPosition(sim.getObject('/Doggy/RR_foot_joint'),sim.getObject('/Doggy/RR_lower_leg_joint'))
print(vertex_2_center)


def get_cg():
    total_mass = 0
    total_cog = [0, 0, 0]
    matrix = sim.getObjectMatrix(robot,-1)
    shape_handles = sim.getObjectsInTree(robot, sim.object_shape_type)

    links_list = ["base_link_visual",
                "RR_upper_leg_link_visual","RR_lower_leg_link_visual","RR_foot_link_visual",
                "RL_upper_leg_link_visual","RL_lower_leg_link_visual","RL_foot_link_visual",
                "FR_upper_leg_link_visual","FR_lower_leg_link_visual","FR_foot_link_visual",
                "FL_upper_leg_link_visual","FL_lower_leg_link_visual","FL_foot_link_visual",
                ]

    for shape in links_list:
        link = sim.getObject(f'/Doggy/{shape}/')
        mass, inertia, cog = sim.getShapeMassAndInertia(link, matrix)
        total_mass += mass
        total_cog = [total_cog[i] + mass * cog[i] for i in range(3)]
    total_cog = [c / total_mass for c in total_cog]



    roll, pitch, yaw = sim.getObjectOrientation(robot, -1)
    inv_roll = get_homgeneous_transform_matrix(roll,0,0,0,"x")
    inv_pitch = get_homgeneous_transform_matrix(pitch,0,0,0,"y")
    inv_yaw = get_homgeneous_transform_matrix(yaw,0,0,0,"z")
    inverse_rotation_matrix =  inv_roll @ inv_pitch @ inv_yaw
    

    homo_matrix = np.array([[1,0,0,total_cog[0]],
                            [0,1,0,total_cog[1]],
                            [0,0,1,total_cog[2]],
                            [0,0,0,1]])
    
    return inverse_rotation_matrix @ homo_matrix



def cg_inside():
    points_dict = discover_base_polygon_points()
    edges = (
        (points_dict["RL"],points_dict["RR"]),
        (points_dict["RR"],points_dict["FR"]),
        (points_dict["FR"],points_dict["FL"]),
        (points_dict["FL"],points_dict["RL"]),
        )
    cg = get_cg()
    xp = cg[0][3]
    yp = cg[1][3]
    cnt = 0
    for edge in edges:
        (x1,y1),(x2,y2) = edge
        if (yp<y1) != (yp<y2) and xp < x1 + ((yp-y1)/(y2-y1))*(x2-x1):
            cnt += 1
    return cnt%2 == 1

def discover_base_polygon_points():
    rl_matrix = get_joint_final_matrix("RL")
    rr_matrix = get_joint_final_matrix("RR")
    fl_matrix = get_joint_final_matrix("FL")
    fr_matrix = get_joint_final_matrix("FR")
    return {"RL":(rl_matrix[0][3],rl_matrix[1][3]),
            "RR":(rr_matrix[0][3],rr_matrix[1][3]),
            "FL":(fl_matrix[0][3],fl_matrix[1][3]),
            "FR":(fr_matrix[0][3],fr_matrix[1][3])}

def get_poligon_area():
    points_dict = discover_base_polygon_points()
    x1 = points_dict["FL"][0]
    y1 = points_dict["FL"][1]
    x2 = points_dict["FR"][0]
    y2 = points_dict["FR"][1]
    x3 = points_dict["RR"][0]
    y3 = points_dict["RR"][1]
    x4 = points_dict["RL"][0]
    y4 = points_dict["RL"][1]
    area = 1/2 * abs(x1*y2+x2*y3+x3*y4+x4*y1 - (y1*x2+y2*x3+y3*x4+y4*x1))
    return area


def get_joint_final_matrix(vertex):
    print(f"{vertex} ---------------------------------" )
    matrix = discover_foot_position(
        vertex_2_center[vertex]["x"],vertex_2_center[vertex]["y"],vertex_2_center[vertex]["z"],\
        upper_leg_lenght,lower_leg_lenght,\
        sim.getJointPosition(sim.getObject(f'/Doggy/{vertex}_upper_leg_joint')),sim.getJointPosition(sim.getObject(f'/Doggy/{vertex}_lower_leg_joint'))
        )
    return matrix

def discover_foot_position(dx,dy,dz,upper_length,lower_length,theta_1,theta_2):
    roll, pitch, yaw = sim.getObjectOrientation(robot, -1)
    inv_roll = get_homgeneous_transform_matrix(roll,0,0,0,"x")
    inv_pitch = get_homgeneous_transform_matrix(pitch,0,0,0,"y")
    inv_yaw = get_homgeneous_transform_matrix(yaw,0,0,0,"z")

    r_0_1 = get_homgeneous_transform_matrix(theta_1,dx,dy,dz,"y")
    r_1_2 = get_homgeneous_transform_matrix(-math.pi/2,0,0,0,"x")
    r_2_3 = get_homgeneous_transform_matrix(theta_2,0,upper_length,0,"z")
    r_3_4 = get_homgeneous_transform_matrix(0,0,lower_length,0,"x")

    return_matrix = inv_roll @ inv_pitch @ inv_yaw
    return  return_matrix @ (((r_0_1 @ r_1_2) @ r_2_3) @ r_3_4)

def get_homgeneous_transform_matrix(theta,dx,dy,dz,axis):
    c = np.cos(theta)
    s = np.sin(theta)
    if axis == "x":
        matrix = np.array([
            [1, 0, 0,dx],
            [0, c,-s,dy],
            [0, s, c,dz],
            [0, 0, 0, 1]])
    if axis == "y":
        matrix = np.array([
            [ c, 0, s,dx],
            [ 0, 1, 0,dy],
            [-s, 0, c,dz],
            [ 0, 0, 0, 1]])
    if axis == "z":
        matrix = np.array([
            [c,-s, 0,dx],
            [s, c, 0,dy],
            [0, 0, 1,dz],
            [0, 0, 0, 1]])
    return matrix
        

{'RL': {'x': -0.1999999999999993, 'y': 0.24999999999999822, 'z': -4.440892098500626e-16}, 'RR': {'x': -0.19999999999999662, 'y': -0.25000000000000266, 'z': -4.440892098500626e-16}, 'FL': {'x': 0.20000000000000018, 'y': 0.25, 'z': 0.0}, 'FR': {'x': 0.1999999999999993, 'y': -0.2500000000000009, 'z': 0.0}}


In [11]:
sim.getJointPosition(sim.getObject(f'/Doggy/FR_lower_leg_joint'))

-0.0013941732905373705

In [6]:
print(get_poligon_area())

RL ---------------------------------
RR ---------------------------------
FL ---------------------------------
FR ---------------------------------
0.12614857640176816


In [28]:
print(get_joint_final_matrix("RR"))
print("----"*40)
print(get_joint_final_matrix("RL"))
print("----"*40)
print(get_joint_final_matrix("FR"))
print("----"*40)
print(get_joint_final_matrix("FL"))
print("----"*40)
print(get_cg())
print(cg_inside())



RR ---------------------------------
[[ 8.66025404e-01 -5.00000000e-01  6.28418398e-17 -5.14711432e-01]
 [-1.25241866e-16 -9.12415954e-17  1.00000000e+00 -2.50000000e-01]
 [-5.00000000e-01 -8.66025404e-01 -1.41638472e-16  8.49364905e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
----------------------------------------------------------------------------------------------------------------------------------------------------------------
RL ---------------------------------
[[ 8.66025404e-01 -5.00000000e-01  6.28418398e-17 -5.14711432e-01]
 [-1.25241866e-16 -9.12415954e-17  1.00000000e+00  2.50000000e-01]
 [-5.00000000e-01 -8.66025404e-01 -1.41638472e-16  8.49364905e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
----------------------------------------------------------------------------------------------------------------------------------------------------------------
FR ---------------------------------
[[ 8.66025404e-01 -5.00000000

In [135]:
sim.getObjectFloatParameter(sim.getObject(f"/Doggy/RR_upper_leg_joint"), sim.jointfloatparam_velocity)

(1, 0.2042988477895982)

In [138]:
matrix = sim.getObjectMatrix(robot, -1)
print(matrix[0])

print(sim.getObjectOrientation(robot, -1))

0.9714468802420952
[0.18139284641515702, -0.18056809086485878, 0.1582672851761023]


In [6]:
import torch
from torch import nn
from torch import optim


class Test_net(nn.Module):
    def __init__(self,input_size,inner_dimensions,output_size,lr):
        super().__init__()
        in_features = input_size
        critic_layers = []
        for out_features in inner_dimensions:
            critic_layers.append(nn.Linear(in_features, out_features))
            critic_layers.append(nn.ReLU())
            in_features = out_features
        
        critic_layers.append(nn.Linear(in_features, output_size))

        self.critic = nn.Sequential(*critic_layers)
        self.optimizer = optim.Adam(self.parameters(),lr=lr)

        
    def forward(self,state):
        value = self.critic(state)
        return value






In [7]:
net = Test_net(5,[10,10],1,0.001)

In [16]:
net(torch.tensor([[10,3,1,3,4],[2,1,4,45,3],[5,12,4,5,1],[4,32,5,1,5],[10,1,4,1,2]],dtype=torch.float))

tensor([[-0.0765],
        [-1.0408],
        [-0.3807],
        [-1.0221],
        [-0.0337]], grad_fn=<AddmmBackward0>)

In [18]:
import numpy as np
from coppeliasim_zmqremoteapi_client import *
import math


client = RemoteAPIClient()
sim = client.require('sim')
robot = sim.getObject('/Doggy/')
target = sim.getObject('/Target')

In [30]:
robot = sim.getObject('/Doggy/')
matrix = sim.getObjectMatrix(robot,-1)
sim.getShapeMassAndInertia(robot,matrix)

(5.0,
 [0.16666666666666669,
  0.0,
  0.0,
  0.0,
  0.21666666666666667,
  0.0,
  0.0,
  0.0,
  0.08333333333333334],
 [0.0, 0.0, 0.0])

In [54]:
total_mass = 0
total_cog = [0, 0, 0]
matrix = sim.getObjectMatrix(robot,-1)
shape_handles = sim.getObjectsInTree(robot, sim.object_shape_type)



for shape in links_list:
    link = sim.getObject(f'/Doggy/{shape}/')
    mass, inertia, cog = sim.getShapeMassAndInertia(link, matrix)
    print(mass)
    total_mass += mass
    total_cog = [total_cog[i] + mass * cog[i] for i in range(3)]
total_cog = [c / total_mass for c in total_cog]
print(total_cog)



5.0
1.0
1.0
0.5
1.0
1.0
0.5
1.0
1.0
0.5
1.0
1.0
0.5
[-0.047140452079105014, -1.295260195396016e-17, -0.14142135623730212]


In [7]:
def get_homgeneous_transform_matrix(theta,dx,dy,dz,axis):
    c = np.cos(theta)
    s = np.sin(theta)
    if axis == "x":
        matrix = np.array([
            [1, 0, 0,dx],
            [0, c,-s,dy],
            [0, s, c,dz],
            [0, 0, 0, 1]])
    if axis == "y":
        matrix = np.array([
            [ c, 0, s,dx],
            [ 0, 1, 0,dy],
            [-s, 0, c,dz],
            [ 0, 0, 0, 1]])
    if axis == "z":
        matrix = np.array([
            [c,-s, 0,dx],
            [s, c, 0,dy],
            [0, 0, 1,dz],
            [0, 0, 0, 1]])
    return matrix

total_mass = 0
total_cog = [0, 0, 0]
matrix = sim.getObjectMatrix(robot,-1)
shape_handles = sim.getObjectsInTree(robot, sim.object_shape_type)

links_list = ["base_link_visual",
              "RR_upper_leg_link_visual","RR_lower_leg_link_visual","RR_foot_link_visual",
              "RL_upper_leg_link_visual","RL_lower_leg_link_visual","RL_foot_link_visual",
              "FR_upper_leg_link_visual","FR_lower_leg_link_visual","FR_foot_link_visual",
              "FL_upper_leg_link_visual","FL_lower_leg_link_visual","FL_foot_link_visual",
              ]

for shape in links_list:
    link = sim.getObject(f'/Doggy/{shape}/')
    mass, inertia, cog = sim.getShapeMassAndInertia(link, matrix)
    total_mass += mass
    total_cog = [total_cog[i] + mass * cog[i] for i in range(3)]
total_cog = [c / total_mass for c in total_cog]



roll, pitch, yaw = sim.getObjectOrientation(robot, -1)
inv_roll = get_homgeneous_transform_matrix(roll,0,0,0,"x")
inv_pitch = get_homgeneous_transform_matrix(pitch,0,0,0,"y")
inv_yaw = get_homgeneous_transform_matrix(yaw,0,0,0,"z")
inverse_rotation_matrix =  inv_roll @ inv_pitch @ inv_yaw
 

homo_matrix = np.array([[1,0,0,total_cog[0]],
                        [0,1,0,total_cog[1]],
                        [0,0,1,total_cog[2]],
                        [0,0,0,1]])

print(homo_matrix)
print("-"*40)
print(inverse_rotation_matrix @ homo_matrix)

print(total_cog)
print("-"*40)
total_cog_global = inverse_rotation_matrix @ np.array([total_cog[0], total_cog[1], total_cog[2], 1])
print(total_cog_global)

[[ 1.          0.          0.         -0.04714045]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.         -0.14142136]
 [ 0.          0.          0.          1.        ]]
----------------------------------------
[[ 1.00000000e+00  9.81307787e-18  4.13002965e-13 -4.71404521e-02]
 [-9.81307787e-18  1.00000000e+00  2.94392336e-17 -3.70074342e-18]
 [-4.13002965e-13 -2.94392336e-17  1.00000000e+00 -1.41421356e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[-0.04714045207910521, 0.0, -0.14142135623730182]
----------------------------------------
[-4.71404521e-02 -3.70074342e-18 -1.41421356e-01  1.00000000e+00]


In [10]:
results = sim.getObjectOrientation(robot, -1)
print(results)

[0.02776512001710126, 0.005673236206217875, -3.1277133228755063]
